name: Mobile Build CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 游끵 Checkout
        uses: actions/checkout@v3

      - name: 丘뙖잺 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # Eliminamos la opci칩n autom치tica de cache para evitar el error 400
          # npm install ya es bastante r치pido con package-lock.json

      - name: 游 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 游닍 Install dependencies
        run: |
          npm ci --legacy-peer-deps
          # Usamos 'npm ci' en lugar de 'npm install' porque es m치s r치pido
          # y est치 dise침ado espec칤ficamente para entornos de integraci칩n continua (CI)
          # ya que usa exactamente lo que hay en tu package-lock.json

      - name: 游 Build APK (Preview)
        # Si es un Pull Request, genera solo el APK de pruebas
        if: github.event_name == 'pull_request'
        run: eas build --platform android --profile preview --non-interactive

      - name: 游끥 Build Production
        # Si es un Push a main, genera la versi칩n de producci칩n
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: eas build --platform android --profile production --non-interactive