name: Mobile Build CI/CD
on:
  push:
    branches: [ main, develop ] # Escucha cambios en ambas ramas

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout
        uses: actions/checkout@v3

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ğŸ›  Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: npm

      - name: ğŸ“¦ Install dependencies
        run: npm ci --legacy-peer-deps

      # --- LÃ“GICA DE DESARROLLO ---
      - name: ğŸ›  Build Development APK
        if: github.ref == 'refs/heads/develop'
        run: eas build --platform android --profile development --non-interactive

      # --- LÃ“GICA DE PRODUCCIÃ“N ---
      - name: ğŸš€ Build Production APK
        if: github.ref == 'refs/heads/main'
        run: eas build --platform android --profile production --non-interactive